apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: email-api
  template:
    metadata:
      labels:
        app: email-api
    spec:
      containers:
      - name: email-api
        image: email-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: email-api
spec:
  selector:
    app: email-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
