apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spam-checker
  template:
    metadata:
      labels:
        app: spam-checker
    spec:
      containers:
      - name: spam-checker
        image: spam-checker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: spam-checker
spec:
  selector:
    app: spam-checker
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
